# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb347f9d84c447b996d605a200f519b8cab9035004e40a01e4820e6fdbb5dfc2f70dd51b415ec145567b2e31266fb869fee1e281239241615928d0ea1e2d51f7

test:
  secret_key_base: d9378e421f2b8c0e565c69f75b2cc528c7f76a517488ca2e31188453e1176a5314f9281bd693f323d9b7a2c20b86e1823c54b4243154b0954deab4204298cf41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
